#!/bin/bash

set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
TURBO_ROOT="${TURBO_ROOT:-$PROJECT_ROOT/external/turbo_mingru_decoder}"
SEED_START="${SEED_START:-7}"
NUM_SEEDS="${NUM_SEEDS:-30}"
SUITE_TAG="${SUITE_TAG:-$(date -u +%Y%m%d_%H%M%S)}"
TURBOAE_SUITE_DIR="${TURBOAE_SUITE_DIR:-$PROJECT_ROOT/results/turboae_long_block_hpc_${SUITE_TAG}}"
MAX_ARRAY_TASKS="${MAX_ARRAY_TASKS:-32}"
MAX_PARALLEL="${MAX_PARALLEL:-}"
SLURM_SCRIPT="$PROJECT_ROOT/hpc/slurm_turboae_long_block_array.sh"
AGGREGATE_SCRIPT="$PROJECT_ROOT/hpc/slurm_turboae_long_block_aggregate.sh"
HPC_USE_CONDA="${HPC_USE_CONDA:-0}"

TURBOAE_CHANNEL="${TURBOAE_CHANNEL:-AWGN}"
TURBOAE_LENGTHS="${TURBOAE_LENGTHS:-64}"
TURBOAE_MODES="${TURBOAE_MODES:-analytic,checkpoint}"
TURBOAE_MODEL_TYPE="${TURBOAE_MODEL_TYPE:-cnn_turbo}"
TURBOAE_EPOCHS="${TURBOAE_EPOCHS:-300}"
TURBOAE_BATCH_SIZE="${TURBOAE_BATCH_SIZE:-500}"
TURBOAE_SAMPLE_SIZE="${TURBOAE_SAMPLE_SIZE:-50000}"
TURBOAE_EVAL_NUM_BLOCKS="${TURBOAE_EVAL_NUM_BLOCKS:-50000}"
TURBOAE_EVAL_BATCHES="${TURBOAE_EVAL_BATCHES:-20}"
TURBOAE_EVAL_EVERY="${TURBOAE_EVAL_EVERY:-10}"
TURBOAE_SAVE_EVERY="${TURBOAE_SAVE_EVERY:-25}"
TURBOAE_DEC_BS_FAC="${TURBOAE_DEC_BS_FAC:-1}"
TURBOAE_ENC_MICRO_BATCH_SIZE="${TURBOAE_ENC_MICRO_BATCH_SIZE:-0}"
TURBOAE_DEC_MICRO_BATCH_SIZE="${TURBOAE_DEC_MICRO_BATCH_SIZE:-0}"
TURBOAE_LEARNING_RATE="${TURBOAE_LEARNING_RATE:-0.0002}"
TURBOAE_WEIGHT_DECAY="${TURBOAE_WEIGHT_DECAY:-0.01}"
TURBOAE_GRAD_CLIP_NORM="${TURBOAE_GRAD_CLIP_NORM:-1.0}"
TURBOAE_EBNO_DB="${TURBOAE_EBNO_DB:-4.0}"
TURBOAE_RATE="${TURBOAE_RATE:-0.5}"
TURBOAE_DECODER_EBNO_OFFSET_LOW="${TURBOAE_DECODER_EBNO_OFFSET_LOW:--3.5}"
TURBOAE_DECODER_EBNO_OFFSET_HIGH="${TURBOAE_DECODER_EBNO_OFFSET_HIGH:-0.0}"
TURBOAE_ALLOW_TF32="${TURBOAE_ALLOW_TF32:-1}"
TURBOAE_AMP="${TURBOAE_AMP:-0}"
TURBOAE_AMP_DTYPE="${TURBOAE_AMP_DTYPE:-bfloat16}"
TURBOAE_COMPILE_MODELS="${TURBOAE_COMPILE_MODELS:-0}"
TURBOAE_ENABLE_GPU_WARMUP="${TURBOAE_ENABLE_GPU_WARMUP:-0}"
TURBOAE_LR_PLATEAU_PATIENCE_EVALS="${TURBOAE_LR_PLATEAU_PATIENCE_EVALS:-0}"
TURBOAE_LR_PLATEAU_FACTOR="${TURBOAE_LR_PLATEAU_FACTOR:-0.5}"
TURBOAE_LR_PLATEAU_MAX_REDUCTIONS="${TURBOAE_LR_PLATEAU_MAX_REDUCTIONS:-0}"
TURBOAE_LR_PLATEAU_MIN_LR="${TURBOAE_LR_PLATEAU_MIN_LR:-0.00001}"
TRAIN_CHANNEL_IMPLANT="${TRAIN_CHANNEL_IMPLANT:-1}"
CHANNEL_IMPLANT_CHECKPOINT="${CHANNEL_IMPLANT_CHECKPOINT:-}"
CHANNEL_IMPLANT_DATASET_SIZE="${CHANNEL_IMPLANT_DATASET_SIZE:-120000}"
CHANNEL_IMPLANT_EVAL_SIZE="${CHANNEL_IMPLANT_EVAL_SIZE:-100000}"
CHANNEL_IMPLANT_BATCH_SIZE="${CHANNEL_IMPLANT_BATCH_SIZE:-512}"
CHANNEL_IMPLANT_EPOCHS="${CHANNEL_IMPLANT_EPOCHS:-30}"
CHANNEL_IMPLANT_SWD_PROJECTIONS="${CHANNEL_IMPLANT_SWD_PROJECTIONS:-128}"
CHANNEL_IMPLANT_ANCHOR_COUNT="${CHANNEL_IMPLANT_ANCHOR_COUNT:-128}"
CHANNEL_IMPLANT_ANCHOR_SAMPLES="${CHANNEL_IMPLANT_ANCHOR_SAMPLES:-64}"
CHANNEL_IMPLANT_ANCHOR_SWD_PROJECTIONS="${CHANNEL_IMPLANT_ANCHOR_SWD_PROJECTIONS:-64}"
CHANNEL_IMPLANT_SINKHORN_MIN_EPSILON="${CHANNEL_IMPLANT_SINKHORN_MIN_EPSILON:-0.001}"
CHANNEL_IMPLANT_SINKHORN_ITERATIONS="${CHANNEL_IMPLANT_SINKHORN_ITERATIONS:-10}"
CHANNEL_IMPLANT_FIBER_GENERATED_SAMPLES="${CHANNEL_IMPLANT_FIBER_GENERATED_SAMPLES:-4}"
CHANNEL_IMPLANT_FIBER_POSITIVE_SAMPLES="${CHANNEL_IMPLANT_FIBER_POSITIVE_SAMPLES:-4}"
CHANNEL_IMPLANT_FIBER_REFERENCE_SAMPLES="${CHANNEL_IMPLANT_FIBER_REFERENCE_SAMPLES:-4}"

mkdir -p "$PROJECT_ROOT/logs"
mkdir -p "$TURBOAE_SUITE_DIR"

if (( NUM_SEEDS < 1 )); then
  echo "NUM_SEEDS must be at least 1" >&2
  exit 1
fi
if (( MAX_ARRAY_TASKS < 1 )); then
  echo "MAX_ARRAY_TASKS must be at least 1" >&2
  exit 1
fi

ARRAY_TASK_COUNT="$NUM_SEEDS"
if (( ARRAY_TASK_COUNT > MAX_ARRAY_TASKS )); then
  ARRAY_TASK_COUNT="$MAX_ARRAY_TASKS"
fi

ARRAY_END=$((ARRAY_TASK_COUNT - 1))
ARRAY_SPEC="0-${ARRAY_END}"
if [[ -n "$MAX_PARALLEL" ]]; then
  ARRAY_SPEC="${ARRAY_SPEC}%${MAX_PARALLEL}"
fi

export PROJECT_ROOT
export TURBO_ROOT
export SEED_START
export NUM_SEEDS
export TURBOAE_SUITE_DIR
export ARRAY_TASK_COUNT
export HPC_USE_CONDA
export TURBOAE_CHANNEL
export TURBOAE_LENGTHS
export TURBOAE_MODES
export TURBOAE_MODEL_TYPE
export TURBOAE_EPOCHS
export TURBOAE_BATCH_SIZE
export TURBOAE_SAMPLE_SIZE
export TURBOAE_EVAL_NUM_BLOCKS
export TURBOAE_EVAL_BATCHES
export TURBOAE_EVAL_EVERY
export TURBOAE_SAVE_EVERY
export TURBOAE_DEC_BS_FAC
export TURBOAE_ENC_MICRO_BATCH_SIZE
export TURBOAE_DEC_MICRO_BATCH_SIZE
export TURBOAE_LEARNING_RATE
export TURBOAE_WEIGHT_DECAY
export TURBOAE_GRAD_CLIP_NORM
export TURBOAE_EBNO_DB
export TURBOAE_RATE
export TURBOAE_DECODER_EBNO_OFFSET_LOW
export TURBOAE_DECODER_EBNO_OFFSET_HIGH
export TURBOAE_ALLOW_TF32
export TURBOAE_AMP
export TURBOAE_AMP_DTYPE
export TURBOAE_COMPILE_MODELS
export TURBOAE_ENABLE_GPU_WARMUP
export TURBOAE_LR_PLATEAU_PATIENCE_EVALS
export TURBOAE_LR_PLATEAU_FACTOR
export TURBOAE_LR_PLATEAU_MAX_REDUCTIONS
export TURBOAE_LR_PLATEAU_MIN_LR
export TRAIN_CHANNEL_IMPLANT
export CHANNEL_IMPLANT_CHECKPOINT
export CHANNEL_IMPLANT_DATASET_SIZE
export CHANNEL_IMPLANT_EVAL_SIZE
export CHANNEL_IMPLANT_BATCH_SIZE
export CHANNEL_IMPLANT_EPOCHS
export CHANNEL_IMPLANT_SWD_PROJECTIONS
export CHANNEL_IMPLANT_ANCHOR_COUNT
export CHANNEL_IMPLANT_ANCHOR_SAMPLES
export CHANNEL_IMPLANT_ANCHOR_SWD_PROJECTIONS
export CHANNEL_IMPLANT_SINKHORN_MIN_EPSILON
export CHANNEL_IMPLANT_SINKHORN_ITERATIONS
export CHANNEL_IMPLANT_FIBER_GENERATED_SAMPLES
export CHANNEL_IMPLANT_FIBER_POSITIVE_SAMPLES
export CHANNEL_IMPLANT_FIBER_REFERENCE_SAMPLES

echo "[submit] project_root: $PROJECT_ROOT"
echo "[submit] turbo_root: $TURBO_ROOT"
echo "[submit] suite_dir: $TURBOAE_SUITE_DIR"
echo "[submit] seeds: $SEED_START..$((SEED_START + NUM_SEEDS - 1))"
echo "[submit] channel: $TURBOAE_CHANNEL"
echo "[submit] lengths: $TURBOAE_LENGTHS"
echo "[submit] modes: $TURBOAE_MODES"
echo "[submit] epochs: $TURBOAE_EPOCHS"
echo "[submit] batch_size: $TURBOAE_BATCH_SIZE"
echo "[submit] sample_size: $TURBOAE_SAMPLE_SIZE"
echo "[submit] eval_num_blocks: $TURBOAE_EVAL_NUM_BLOCKS"
echo "[submit] ebno_db: $TURBOAE_EBNO_DB"
echo "[submit] rate: $TURBOAE_RATE"
echo "[submit] train_channel_implant: $TRAIN_CHANNEL_IMPLANT"
echo "[submit] channel_implant_epochs: $CHANNEL_IMPLANT_EPOCHS"
echo "[submit] logical_seed_tasks: $NUM_SEEDS"
echo "[submit] max_array_tasks: $MAX_ARRAY_TASKS"
echo "[submit] submitted_array_tasks: $ARRAY_TASK_COUNT"
echo "[submit] array: $ARRAY_SPEC"

ARRAY_JOB_ID=$(sbatch --parsable --chdir="$PROJECT_ROOT" --array="$ARRAY_SPEC" "$SLURM_SCRIPT")
echo "[submit] array_job_id: $ARRAY_JOB_ID"
echo "[submit] aggregate after completion with:"
echo "export PROJECT_ROOT=\"$PROJECT_ROOT\""
echo "export TURBOAE_SUITE_DIR=\"$TURBOAE_SUITE_DIR\""
echo "export SEED_START=$SEED_START"
echo "export NUM_SEEDS=$NUM_SEEDS"
echo "export TURBOAE_LENGTHS=\"$TURBOAE_LENGTHS\""
echo "export TURBOAE_MODES=\"$TURBOAE_MODES\""
echo "sbatch --chdir=\"$PROJECT_ROOT\" --dependency=afterok:${ARRAY_JOB_ID} \"$AGGREGATE_SCRIPT\""
