from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt


VARIANT_LABELS = {
    "analytic": "Analytic",
    "kernel_target": "Kernel target",
    "kernel_joint": "Kernel joint",
    "joint_sinkhorn": "Joint Sinkhorn",
    "fiber_sinkhorn": "Condition-wise Sinkhorn",
}

COLORS = {
    "analytic": "#4d4d4d",
    "kernel_target": "#54a24b",
    "kernel_joint": "#b279a2",
    "joint_sinkhorn": "#ff9da6",
    "fiber_sinkhorn": "#9d755d",
}

MARKERS = {
    "analytic": "o",
    "kernel_target": "s",
    "kernel_joint": "^",
    "joint_sinkhorn": "D",
    "fiber_sinkhorn": "P",
}

MC_REPORT_FLOORS = {
    ("SSPA", "ber"): 1.67e-6,
    ("SSPA", "ser"): 1.0e-5,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot journal W-Flow BER/SER curves.")
    parser.add_argument("--summary-csv", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=Path("Journal_version/figures"))
    parser.add_argument("--latex-out", type=Path, default=None)
    parser.add_argument("--channels", type=str, default="")
    parser.add_argument("--variants", type=str, default="analytic,kernel_target,kernel_joint,joint_sinkhorn,fiber_sinkhorn")
    return parser.parse_args()


def parse_csv_list(text: str) -> list[str]:
    return [part.strip() for part in text.split(",") if part.strip()]


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def display_curve_values(channel: str, metric: str, means: list[float], sems: list[float]) -> tuple[list[float], list[list[float]], list[bool]]:
    floor = MC_REPORT_FLOORS.get((channel, metric))
    display_means: list[float] = []
    lower_errors: list[float] = []
    upper_errors: list[float] = []
    clipped: list[bool] = []
    for mean, sem in zip(means, sems):
        if floor is not None and mean < floor:
            display_means.append(floor)
            lower_errors.append(0.0)
            upper_errors.append(0.0)
            clipped.append(True)
            continue
        display_means.append(mean)
        min_positive = floor if floor is not None else max(mean * 1e-3, 1e-12)
        lower_errors.append(max(0.0, min(sem, mean - min_positive)))
        upper_errors.append(max(0.0, sem))
        clipped.append(False)
    return display_means, [lower_errors, upper_errors], clipped


def plot_channel(channel: str, variants: list[str], rows: list[dict[str, str]], out_dir: Path) -> None:
    channel_rows = [row for row in rows if row["channel"] == channel]
    fig, axes = plt.subplots(1, 2, figsize=(8.8, 3.6), sharex=True)
    for ax, metric, ylabel in [(axes[0], "ber", "BER"), (axes[1], "ser", "SER")]:
        for variant in variants:
            pts = sorted(
                [row for row in channel_rows if row["variant"] == variant],
                key=lambda row: float(row["ebno_db"]),
            )
            if not pts:
                continue
            xs = [float(row["ebno_db"]) for row in pts]
            raw_ys = [float(row[f"{metric}_mean"]) for row in pts]
            raw_yerr = [float(row[f"{metric}_sem"]) for row in pts]
            ys, yerr, clipped = display_curve_values(channel, metric, raw_ys, raw_yerr)
            ax.errorbar(
                xs,
                ys,
                yerr=yerr,
                label=VARIANT_LABELS.get(variant, variant),
                color=COLORS.get(variant),
                marker=MARKERS.get(variant, "o"),
                linewidth=1.8,
                markersize=4.0,
                capsize=2.0,
            )
            floor = MC_REPORT_FLOORS.get((channel, metric))
            if floor is not None:
                for x, is_clipped in zip(xs, clipped):
                    if is_clipped:
                        ax.text(x, floor * 1.25, "$<$", color=COLORS.get(variant), ha="center", va="bottom", fontsize=7)
        ax.set_yscale("log")
        ax.set_xlabel(r"$E_b/N_0$ (dB)")
        ax.set_ylabel(ylabel)
        ax.grid(True, which="major", linewidth=0.4, alpha=0.35)
        floor = MC_REPORT_FLOORS.get((channel, metric))
        if floor is not None:
            ax.axhline(floor, color="#777777", linewidth=0.6, linestyle=":", alpha=0.65)
    axes[0].set_title(f"{channel} BER")
    axes[1].set_title(f"{channel} SER")
    axes[1].legend(fontsize=7, loc="best", frameon=True)
    fig.tight_layout()
    stem = out_dir / f"wflow_{channel.lower()}_ber_ser_curves"
    fig.savefig(stem.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(stem.with_suffix(".png"), dpi=220, bbox_inches="tight")
    plt.close(fig)


def write_latex_snippet(path: Path, channels: list[str]) -> None:
    lines = [
        "% Auto-generated by scripts/plot_journal_wflow_curves.py.",
        "% Regenerate after the journal W-Flow curve suite has been aggregated.",
        "",
    ]
    for channel in channels:
        stem = f"wflow_{channel.lower()}_ber_ser_curves"
        label = f"fig:wflow-{channel.lower()}-ber-ser-curves"
        lines.extend(
            [
                r"\begin{figure*}[t]",
                r"\centering",
                rf"\includegraphics[width=0.92\textwidth]{{figures/{stem}.pdf}}",
                rf"\caption{{\textbf{{{channel} BER/SER curves for W-Flow channel surrogates.}} Symbolic autoencoders are trained through each surrogate and evaluated on the analytic channel over an $E_b/N_0$ grid. Curves report seed means with standard-error bars; points below the single-run Monte Carlo resolution are clipped to the dotted reporting floor and marked as upper bounds.}}",
                rf"\label{{{label}}}",
                r"\end{figure*}",
                "",
            ]
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    rows = read_rows(args.summary_csv)
    variants = parse_csv_list(args.variants)
    channels = parse_csv_list(args.channels) or sorted({row["channel"] for row in rows})
    args.out_dir.mkdir(parents=True, exist_ok=True)
    for channel in channels:
        plot_channel(channel, variants, rows, args.out_dir)
    latex_out = args.latex_out or (args.out_dir.parent / "wflow_curve_figures.tex")
    write_latex_snippet(latex_out, channels)
    print({"channels": channels, "out_dir": str(args.out_dir), "latex_out": str(latex_out)})


if __name__ == "__main__":
    main()
